allowBuildScripts: '@tailwindcss/oxide,@vercel/speed-insights,esbuild,sharp,unrs-resolver'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
