/**
 * Exportações da API de Cursos
 */

// Categorias
export {
  listCategorias,
  getCategoria,
  createCategoria,
  updateCategoria,
  deleteCategoria,
} from "./categorias";

// Subcategorias
export {
  listSubcategorias,
  getSubcategoria,
  createSubcategoria,
  updateSubcategoria,
  deleteSubcategoria,
} from "./categorias";

// Tipos
export type {
  CategoriaCurso,
  SubcategoriaCurso,
  CreateCategoriaPayload,
  UpdateCategoriaPayload,
  CreateSubcategoriaPayload,
  UpdateSubcategoriaPayload,
  CategoriasListApiResponse,
  CategoriaDetailApiResponse,
  SubcategoriaDetailApiResponse,
  CategoriaCreateApiResponse,
  SubcategoriaCreateApiResponse,
  CategoriasListParams,
  SubcategoriasListParams,
} from "./categorias/types";

// Cursos (core)
export {
  getCursosMeta,
  listCursos,
  createCurso,
  getCursoById,
  updateCurso,
  despublicarCurso,
  excluirCursoDefinitivamente,
  listTurmas,
  getTurmaById,
  createTurma,
  syncTurmaInstrutores,
  appendTurmaEstruturaItem,
  publicarTurma,
  deleteTurma,
  vincularTemplatesAoCurso,
  listInscricoes,
  createInscricao,
  deleteInscricao,
  listInscricoesCurso,
  listCursoAuditoria,
  listProvas,
  getProvaById,
  createProva,
  updateProva,
  deleteProva,
  listProvaTokens,
  createProvaToken,
  getProvaTokenById,
  getProvaTokenByToken,
  listModulos,
  listCertificados,
  createCertificado,
  listCertificadosGlobal,
  createCertificadoGlobal,
  getCertificadoById,
  listMeCertificados,
  listCertificadoModelos,
  verificarCertificadoPorCodigo,
  createEstagio,
  listEstagiosByInscricao,
  listAlunosComInscricao,
  getCursoAlunoDetalhes,
  getCursoAlunoEntrevistas,
  getCursoAlunoEntrevistaOpcoes,
  createCursoAlunoEntrevista,
  updateCursoAluno,
  getVisaoGeral,
  getVisaoGeralFaturamento,
  // API v3 - Meta do Curso
  getCursoMeta,
  // API v3 - Frequência
  listFrequencias,
  listFrequenciasGlobal,
  listFrequenciasByAluno,
  getFrequenciaResumo,
  createFrequencia,
  upsertFrequenciaLancamento,
  upsertFrequenciaLancamentoByAluno,
  updateFrequencia,
  listFrequenciaHistorico,
  listFrequenciaHistoricoByNaturalKey,
  listFrequenciaHistoricoByAluno,
  listFrequenciaHistoricoByAlunoNaturalKey,
  // API v3 - Notas
  listNotas,
  listNotasGlobal,
  listNotasByAluno,
  createNota,
  deleteNotas,
  getNotaHistorico,
  // API v3 - Avaliações (Biblioteca Global)
  listAvaliacoes,
  getAvaliacao,
  listAvaliacaoQuestoes,
  createAvaliacao,
  updateAvaliacao,
  publicarAvaliacao,
  deleteAvaliacao,
  cloneAvaliacaoParaTurma,
  listAvaliacoesTurmas,
  listAvaliacoesInstrutores,
  // API v3 - Estágios (Global)
  listEstagiosGlobal,
  createEstagioGlobal,
  getEstagioById,
  listEstagiosByAluno,
  getEstagioByAluno,
  updateEstagioGlobal,
  vincularAlunosEstagio,
  alocarAlunoEstagioGrupo,
  listEstagioFrequencias,
  listEstagioFrequenciasByAluno,
  listEstagioFrequenciasPeriodo,
  listEstagioFrequenciasPeriodoByAluno,
  upsertEstagioFrequenciaLancamento,
  upsertEstagioFrequenciaLancamentoByAluno,
  listEstagioFrequenciaHistorico,
  listEstagioFrequenciaHistoricoPaginado,
  listEstagioFrequenciaHistoricoByAlunoPaginado,
  concluirEstagioAluno,
  updateEstagioStatus,
  // API v3 - Checkout
  iniciarCheckout,
  getCheckoutPagamento,
  getVagasDisponiveis,
  // API v3 - Agenda
  listAgenda,
} from "./core";
export type {
  CursosModuleMeta as CursosModuleInfoResponse,
  CursosListParams,
  CursosListResponse,
  CreateCursoPayload,
  UpdateCursoPayload,
  Curso,
  CursoMeta,
  CreateTurmaPayload,
  SyncTurmaInstrutoresPayload,
  AppendTurmaEstruturaItemPayload,
  AppendTurmaEstruturaItemResponse,
  UpdateTurmaPayload,
  CreateTurmaEstruturaPayload,
  CreateTurmaEstruturaItemPayload,
  CreateTurmaEstruturaModulePayload,
  CursoTurma,
  TurmaEstruturaTipo,
  VincularTemplatesAoCursoPayload,
  VincularTemplatesAoCursoResponse,
  TurmaInscricao,
  CreateInscricaoPayload,
  StatusInscricao,
  InscricaoCurso,
  ListTurmasParams,
  GetTurmaByIdParams,
  ListInscricoesCursoParams,
  ListInscricoesCursoResponse,
  CursoAuditoriaItem,
  ListCursoAuditoriaParams,
  ListCursoAuditoriaResponse,
  TurmaProva,
  CreateProvaPayload,
  UpdateProvaPayload,
  ProvaToken,
  CreateProvaTokenPayload,
  ListProvaTokensParams,
  ListProvaTokensResponse,
  ProvaTokenResponse,
  CursoModulo,
  TurmaCertificado,
  CertificadoStatus,
  CertificadoModeloResumo,
  ListCertificadosGlobalParams,
  ListCertificadosResponse,
  CreateCertificadoPayload,
  TurmaEstagio,
  CreateEstagioPayload,
  AlunoComInscricao,
  ListAlunosComInscricaoParams,
  ListAlunosComInscricaoResponse,
  CursoAlunoDetalhes,
  CursoAlunoDetalhesResponse,
  CursoAlunoEntrevistaOpcaoItem,
  CursoAlunoEntrevistaOpcoesResponse,
  CursoAlunoCreateEntrevistaPayload,
  CursoAlunoCreateEntrevistaResponse,
  CursoAlunoEntrevistasParams,
  CursoAlunoEntrevistasResponse,
  CursoAlunoInscricao,
  CursoAlunoEndereco,
  CursoAlunoEstatisticas,
  CursoAlunoCursoResumo,
  CursoAlunoTurmaResumo,
  VisaoGeralResponse,
  VisaoGeralData,
  VisaoGeralMetricasGerais,
  VisaoGeralFaturamento,
  VisaoGeralFaturamentoPeriod,
  VisaoGeralFaturamentoHistoricalPoint,
  VisaoGeralFaturamentoTopCurso,
  VisaoGeralFaturamentoTendenciasData,
  VisaoGeralFaturamentoTendenciasResponse,
  VisaoGeralPerformance,
  CursosProximosInicio,
  TurmaProximoInicio,
  CursoFaturamento,
  CursoPerformance,
  CursoTaxaConclusao,
  // API v3 - Frequência
  FrequenciaStatus,
  FrequenciaOrigemTipo,
  FrequenciaModoLancamento,
  Frequencia,
  FrequenciaResumoItem,
  FrequenciaResumoResponse,
  ListFrequenciasParams,
  ListFrequenciasResponse,
  ListFrequenciaResumoParams,
  CreateFrequenciaPayload,
  UpsertFrequenciaLancamentoPayload,
  UpsertFrequenciaLancamentoByAlunoPayload,
  UpdateFrequenciaPayload,
  FrequenciaHistoryEntry,
  FrequenciaHistoryActor,
  FrequenciaAcao,
  ListFrequenciaHistoricoByNaturalKeyParams,
  ListFrequenciaHistoricoByAlunoNaturalKeyParams,
  // API v3 - Notas
  NotaOrigemTipo,
  NotaHistoryAction,
  NotaOrigem,
  NotaHistoryEvent,
  NotaHistoricoAcao,
  NotaHistoricoActor,
  NotaHistoricoSnapshot,
  NotaHistoricoItem,
  NotaLancamento,
  ListNotasParams,
  ListNotasResponse,
  GetNotaHistoricoResponse,
  CreateNotaPayload,
  DeleteNotasParams,
  // API v3 - Avaliações
  AvaliacaoTipo,
  AvaliacaoTipoAtividade,
  AvaliacaoStatus,
  AvaliacaoModalidade,
  AvaliacaoQuestaoTipo,
  AvaliacaoAlternativaInput,
  AvaliacaoAlternativa,
  AvaliacaoQuestaoInput,
  AvaliacaoQuestao,
  AvaliacaoQuestaoLegacy,
  Avaliacao,
  ListAvaliacoesParams,
  ListAvaliacoesResponse,
  CreateAvaliacaoPayload,
  UpdateAvaliacaoPayload,
  CloneAvaliacaoPayload,
  // API v3 - Estágios
  EstagioStatus,
  EstagioModoAlocacao,
  EstagioPeriodicidade,
  EstagioTurno,
  EstagioTipoParticipacao,
  EstagioAlunoStatus,
  EstagioFrequenciaStatus,
  EstagioPeriodo,
  EstagioGrupo,
  EstagioAluno,
  EstagioResumo,
  Estagio,
  ListEstagiosParams,
  ListEstagiosResponse,
  CreateEstagioGlobalPayload,
  CreateEstagioGroupPayload,
  UpdateEstagioGlobalPayload,
  VincularAlunosEstagioPayload,
  AlocarAlunoEstagioGrupoPayload,
  ListEstagioFrequenciasParams,
  ListEstagioFrequenciasPeriodoParams,
  EstagioFrequenciasPeriodoGroup,
  EstagioFrequenciasPeriodoMeta,
  EstagioFrequenciasPeriodoResponse,
  EstagioFrequencia,
  UpsertEstagioFrequenciaPayload,
  ListEstagioFrequenciaHistoricoParams,
  EstagioFrequenciaHistoryActor,
  EstagioFrequenciaHistorySeguranca,
  EstagioFrequenciaHistoricoResponse,
  ConcluirEstagioAlunoResponse,
  UpdateEstagioStatusPayload,
  // API v3 - Certificados
  Certificado,
  CertificadoVerificacao,
  // API v3 - Agenda
  AgendaEventoTipo,
  AulaModalidade,
  AgendaEvento,
  ListAgendaParams,
  // API v3 - Checkout
  CheckoutPayload,
  CheckoutResponse,
  CheckoutPagamentoStatus,
  VagasDisponiveis,
  // API v3 - Materiais
  MaterialTipo,
  AulaMaterial,
  CreateMaterialPayload,
  UpdateMaterialPayload,
  ReordenarMateriaisPayload,
  // API v3 - Categorias
  Subcategoria as SubcategoriaV3,
  Categoria as CategoriaV3,
  // API v3 - Paginação genérica
  Pagination,
  PaginatedResponse,
  ApiResponse,
  ApiError,
} from "./types";
