/**
 * Exportações da API de Cursos
 */

// Categorias
export {
  listCategorias,
  getCategoria,
  createCategoria,
  updateCategoria,
  deleteCategoria,
} from "./categorias";

// Subcategorias
export {
  listSubcategorias,
  getSubcategoria,
  createSubcategoria,
  updateSubcategoria,
  deleteSubcategoria,
} from "./categorias";

// Tipos
export type {
  CategoriaCurso,
  SubcategoriaCurso,
  CreateCategoriaPayload,
  UpdateCategoriaPayload,
  CreateSubcategoriaPayload,
  UpdateSubcategoriaPayload,
  CategoriasListApiResponse,
  CategoriaDetailApiResponse,
  SubcategoriaDetailApiResponse,
  CategoriaCreateApiResponse,
  SubcategoriaCreateApiResponse,
  CategoriasListParams,
  SubcategoriasListParams,
} from "./categorias/types";

// Cursos (core)
export {
  getCursosMeta,
  listCursos,
  createCurso,
  getCursoById,
  updateCurso,
  despublicarCurso,
  listTurmas,
  getTurmaById,
  createTurma,
  listInscricoes,
  createInscricao,
  deleteInscricao,
  listInscricoesCurso,
  listCursoAuditoria,
  listProvas,
  getProvaById,
  createProva,
  updateProva,
  deleteProva,
  listProvaTokens,
  createProvaToken,
  getProvaTokenById,
  getProvaTokenByToken,
  listModulos,
  listCertificados,
  createCertificado,
  createEstagio,
  listAlunosComInscricao,
  getCursoAlunoDetalhes,
  updateCursoAluno,
  getVisaoGeral,
  getVisaoGeralFaturamento,
  // API v3 - Meta do Curso
  getCursoMeta,
  // API v3 - Frequência
  listFrequencias,
  getFrequenciaResumo,
  createFrequencia,
  updateFrequencia,
  // API v3 - Notas
  listNotas,
  createNota,
  deleteNotas,
  // API v3 - Avaliações (Biblioteca Global)
  listAvaliacoes,
  getAvaliacao,
  createAvaliacao,
  updateAvaliacao,
  deleteAvaliacao,
  cloneAvaliacaoParaTurma,
  listAvaliacoesTurmas,
  listAvaliacoesInstrutores,
  // API v3 - Estágios (Global)
  listEstagiosGlobal,
  updateEstagioStatus,
  // API v3 - Checkout
  iniciarCheckout,
  getCheckoutPagamento,
  getVagasDisponiveis,
  // API v3 - Agenda
  listAgenda,
} from "./core";
export type {
  CursosModuleMeta as CursosModuleInfoResponse,
  CursosListParams,
  CursosListResponse,
  CreateCursoPayload,
  UpdateCursoPayload,
  Curso,
  CursoMeta,
  CreateTurmaPayload,
  CursoTurma,
  TurmaInscricao,
  CreateInscricaoPayload,
  StatusInscricao,
  InscricaoCurso,
  ListInscricoesCursoParams,
  ListInscricoesCursoResponse,
  CursoAuditoriaItem,
  ListCursoAuditoriaParams,
  ListCursoAuditoriaResponse,
  TurmaProva,
  CreateProvaPayload,
  UpdateProvaPayload,
  ProvaToken,
  CreateProvaTokenPayload,
  ListProvaTokensParams,
  ListProvaTokensResponse,
  ProvaTokenResponse,
  CursoModulo,
  TurmaCertificado,
  CreateCertificadoPayload,
  TurmaEstagio,
  CreateEstagioPayload,
  AlunoComInscricao,
  ListAlunosComInscricaoParams,
  ListAlunosComInscricaoResponse,
  CursoAlunoDetalhes,
  CursoAlunoDetalhesResponse,
  CursoAlunoInscricao,
  CursoAlunoEndereco,
  CursoAlunoEstatisticas,
  CursoAlunoCursoResumo,
  CursoAlunoTurmaResumo,
  VisaoGeralResponse,
  VisaoGeralData,
  VisaoGeralMetricasGerais,
  VisaoGeralFaturamento,
  VisaoGeralFaturamentoPeriod,
  VisaoGeralFaturamentoHistoricalPoint,
  VisaoGeralFaturamentoTopCurso,
  VisaoGeralFaturamentoTendenciasData,
  VisaoGeralFaturamentoTendenciasResponse,
  VisaoGeralPerformance,
  CursosProximosInicio,
  TurmaProximoInicio,
  CursoFaturamento,
  CursoPerformance,
  CursoTaxaConclusao,
  // API v3 - Frequência
  FrequenciaStatus,
  Frequencia,
  FrequenciaResumoItem,
  FrequenciaResumoResponse,
  ListFrequenciasParams,
  ListFrequenciaResumoParams,
  CreateFrequenciaPayload,
  UpdateFrequenciaPayload,
  // API v3 - Notas
  NotaOrigemTipo,
  NotaHistoryAction,
  NotaOrigem,
  NotaHistoryEvent,
  NotaLancamento,
  ListNotasParams,
  ListNotasResponse,
  CreateNotaPayload,
  DeleteNotasParams,
  // API v3 - Avaliações
  AvaliacaoTipo,
  AvaliacaoTipoAtividade,
  AvaliacaoStatus,
  AvaliacaoModalidade,
  AvaliacaoQuestaoTipo,
  AvaliacaoAlternativaInput,
  AvaliacaoAlternativa,
  AvaliacaoQuestaoInput,
  AvaliacaoQuestao,
  AvaliacaoQuestaoLegacy,
  Avaliacao,
  ListAvaliacoesParams,
  ListAvaliacoesResponse,
  CreateAvaliacaoPayload,
  UpdateAvaliacaoPayload,
  CloneAvaliacaoPayload,
  // API v3 - Estágios
  EstagioStatus,
  Estagio,
  ListEstagiosParams,
  ListEstagiosResponse,
  UpdateEstagioStatusPayload,
  // API v3 - Certificados
  Certificado,
  CertificadoVerificacao,
  // API v3 - Agenda
  AgendaEventoTipo,
  AulaModalidade,
  AgendaEvento,
  ListAgendaParams,
  // API v3 - Checkout
  CheckoutPayload,
  CheckoutResponse,
  CheckoutPagamentoStatus,
  VagasDisponiveis,
  // API v3 - Materiais
  MaterialTipo,
  AulaMaterial,
  CreateMaterialPayload,
  UpdateMaterialPayload,
  ReordenarMateriaisPayload,
  // API v3 - Categorias
  Subcategoria as SubcategoriaV3,
  Categoria as CategoriaV3,
  // API v3 - Paginação genérica
  Pagination,
  PaginatedResponse,
  ApiResponse,
  ApiError,
} from "./types";
