export enum UserRole {
  ADMIN = "ADMIN",
  MODERADOR = "MODERADOR",
  FINANCEIRO = "FINANCEIRO",
  PROFESSOR = "PROFESSOR",
  EMPRESA = "EMPRESA",
  PEDAGOGICO = "PEDAGOGICO",
  RECRUTADOR = "RECRUTADOR",
  PSICOLOGO = "PSICOLOGO",
  ALUNO_CANDIDATO = "ALUNO_CANDIDATO",
}

export const ALL_ROLES: UserRole[] = Object.values(UserRole);
