import type { AdminCompanyPagination } from "@/api/empresas";
import type { Partnership, PartnershipType } from "../types";

export const COMPANY_DASHBOARD_CONFIG = {
  itemsPerPage: 25,
  api: {
    pageSize: 200,
    timeout: 15000,
  },
};

export const TRIAL_PARTNERSHIP_TYPES: PartnershipType[] = [
  "7_dias",
  "15_dias",
  "30_dias",
  "60_dias",
  "90_dias",
  "120_dias",
];

export const DEFAULT_COMPANY_PAGINATION: AdminCompanyPagination = {
  page: 1,
  pageSize: COMPANY_DASHBOARD_CONFIG.api.pageSize,
  total: 0,
  totalPages: 0,
};

export const MOCK_COMPANY_PARTNERSHIPS: Partnership[] = [
  {
    id: "mock-empresa-1",
    tipo: "parceiro",
    inicio: "2024-01-10T12:00:00Z",
    fim: "2024-02-10T12:00:00Z",
    empresa: {
      id: "mock-empresa-1",
      nome: "Advance Tech Consultoria",
      avatarUrl: "https://cdn.advance.com.br/logo.png",
      cidade: "São Paulo",
      estado: "SP",
      descricao: "Consultoria especializada em recrutamento e seleção para empresas de tecnologia.",
      instagram: "https://instagram.com/advancemais",
      linkedin: "https://linkedin.com/company/advancemais",
      codUsuario: "EMP-123456",
      cnpj: "12345678000190",
      ativo: true,
      criadoEm: "2023-11-01T08:30:00Z",
      parceira: true,
      diasTesteDisponibilizados: 30,
    },
    plano: {
      id: "plano-avancado",
      nome: "Plano Avançado",
      valor: "499.90",
      quantidadeVagas: 3,
      vagasPublicadas: 1,
      tipo: "parceiro",
      inicio: "2024-01-10T12:00:00Z",
      fim: "2024-02-10T12:00:00Z",
    },
  },
  {
    id: "mock-empresa-2",
    tipo: "30_dias",
    inicio: "2024-03-01T08:00:00Z",
    fim: "2024-03-31T08:00:00Z",
    empresa: {
      id: "mock-empresa-2",
      nome: "Inova RH Solutions",
      avatarUrl: "https://cdn.advance.com.br/inova.png",
      cidade: "Curitiba",
      estado: "PR",
      descricao: "Agência de recrutamento com foco em inovação.",
      instagram: "https://instagram.com/inovarh",
      linkedin: "https://linkedin.com/company/inovarh",
      codUsuario: "EMP-654321",
      cnpj: "98765432000109",
      ativo: false,
      criadoEm: "2024-02-10T10:15:00Z",
      parceira: false,
      diasTesteDisponibilizados: 30,
    },
    plano: {
      id: "plano-essencial",
      nome: "Plano Essencial",
      valor: "199.90",
      quantidadeVagas: 2,
      vagasPublicadas: 2,
      tipo: "30_dias",
      inicio: "2024-03-01T08:00:00Z",
      fim: "2024-03-31T08:00:00Z",
    },
  },
  {
    id: "mock-empresa-3",
    tipo: "15_dias",
    inicio: "2024-04-05T09:30:00Z",
    fim: "2024-04-20T09:30:00Z",
    empresa: {
      id: "mock-empresa-3",
      nome: "RH Startups Brasil",
      avatarUrl: "https://cdn.advance.com.br/rhstartups.png",
      cidade: "Belo Horizonte",
      estado: "MG",
      descricao: "Conectando startups a talentos de alto impacto.",
      instagram: "https://instagram.com/rhstartups",
      linkedin: "https://linkedin.com/company/rhstartups",
      codUsuario: "EMP-789012",
      cnpj: "19283746000155",
      ativo: true,
      criadoEm: "2024-04-01T11:45:00Z",
      parceira: false,
      diasTesteDisponibilizados: 15,
    },
    plano: {
      id: "plano-start",
      nome: "Plano Start",
      valor: "149.90",
      quantidadeVagas: 1,
      vagasPublicadas: 0,
      tipo: "15_dias",
      inicio: "2024-04-05T09:30:00Z",
      fim: "2024-04-20T09:30:00Z",
    },
  },
];
