export {
  listPlanosEmpresariais,
  getPlanoEmpresarialById,
  createPlanoEmpresarial,
  updatePlanoEmpresarial,
  deletePlanoEmpresarial,
} from "./planos-empresariais";

export type {
  PlanoEmpresarialBackendResponse,
  CreatePlanoEmpresarialPayload,
  UpdatePlanoEmpresarialPayload,
  PlanoEmpresarialListApiResponse,
  PlanoEmpresarialDetailApiResponse,
  PlanoEmpresarialCreateApiResponse,
  PlanoEmpresarialUpdateApiResponse,
  PlanoEmpresarialDeleteApiResponse,
  PlanoEmpresarialErrorResponse,
  PlanoEmpresarialValidationError,
  PlanoEmpresarialNotFoundError,
  PlanoEmpresarialLimitReachedError,
  PlanoEmpresarialUnauthorizedError,
  PlanoEmpresarialForbiddenError,
} from "./planos-empresariais/types";

export {
  listAdminCompanies,
  getAdminCompanyById,
  getMyCompany,
  getAdminCompanyConsolidated,
  createAdminCompany,
  updateAdminCompany,
  updateAdminCompanyPlano,
  createAdminCompanyPlano,
  listAdminCompanyPayments,
  listAdminCompanyBans,
  createAdminCompanyBan,
  listAdminCompanyVacancies,
  listMyCompanyVacancies,
  listAdminCompanyVacanciesInReview,
  approveAdminCompanyVacancy,
  listAdminCompanyUserBans,
  createAdminCompanyUserBan,
  revokeAdminCompanyUserBan,
  validateAdminCompanyCnpj,
  validateAdminCompanyCpf,
} from "./admin";

export type {
  AdminCompanyDetail,
  AdminCompanyDetailResponse,
  AdminCompanyListItem,
  AdminCompanyPagination,
  AdminCompanyPlanoPayload,
  UpdateAdminCompanyPlanoPayload,
  CreateAdminCompanyPlanoPayload,
  AdminCompanyPlano,
  AdminCompanyPlanMode,
  AdminCompanyStatus,
  AdminCompanyPagamento,
  AdminCompanyBanItem,
  CreateAdminCompanyPayload,
  AdminCompanyListParams,
  AdminCompanyListResponse,
  AdminCompanyListApiResponse,
  UpdateAdminCompanyPayload,
  AdminCompanyPaymentParams,
  AdminCompanyBanParams,
  CreateAdminCompanyBanPayload,
  AdminCompanyPaymentHistoryResponse,
  AdminCompanyBanHistoryResponse,
  AdminCompanyBanDetailResponse,
  AdminCompanyPaymentLog,
  AdminCompanyVagaParams,
  AdminCompanyVagaItem,
  AdminCompanyVagaListResponse,
  AdminCompanyVagaDetailResponse,
  AdminCompanyVacancyStatus,
  AdminCompanyConsolidatedResponse,
  AdminCompanyConsolidatedEmpresa,
  AdminCompanyConsolidatedPlanos,
  AdminCompanyConsolidatedPagamentos,
  AdminCompanyConsolidatedVagas,
  AdminCompanyConsolidatedCandidaturas,
  AdminCompanyConsolidatedBloqueios,
  AdminCompanyConsolidatedAuditoria,
  AdminCompanyAuditoriaItem,
  AdminCompanyConsolidatedApiResponse,
  BanItem,
  BanListResponse,
  CreateBanPayload,
  RevokeBanPayload,
  BanResponse,
  BanType,
  BanReason,
  BanStatus,
} from "./admin/types";

export {
  listEmpresaVagaCategorias,
  getEmpresaVagaCategoria,
  createEmpresaVagaCategoria,
  updateEmpresaVagaCategoria,
  deleteEmpresaVagaCategoria,
  listEmpresaVagaSubcategorias,
  getEmpresaVagaSubcategoria,
  createEmpresaVagaSubcategoria,
  updateEmpresaVagaSubcategoria,
  deleteEmpresaVagaSubcategoria,
} from "./vagas/categorias";

export type {
  EmpresaVagaCategoria,
  EmpresaVagaSubcategoria,
  CreateEmpresaVagaCategoriaPayload,
  UpdateEmpresaVagaCategoriaPayload,
  CreateEmpresaVagaSubcategoriaPayload,
  UpdateEmpresaVagaSubcategoriaPayload,
  EmpresaVagaCategoriasListApiResponse,
  EmpresaVagaCategoriaDetailApiResponse,
  EmpresaVagaSubcategoriaDetailApiResponse,
  EmpresaVagaCategoriaCreateApiResponse,
  EmpresaVagaSubcategoriaCreateApiResponse,
  EmpresaVagaCategoriasListParams,
  EmpresaVagaErrorResponse,
} from "./vagas/categorias/types";

// Processos seletivos por vaga
export {
  listVagaProcessos,
  createVagaProcesso,
  getVagaProcessoById,
  updateVagaProcesso,
  deleteVagaProcesso,
} from "./vagas/processos";
export type {
  VagaProcesso,
  VagaProcessoListParams,
  VagaProcessoListResponse,
  CreateVagaProcessoPayload,
  UpdateVagaProcessoPayload,
} from "./vagas/processos/types";

// Clientes (vinculações de planos)
export {
  listClientesPlanos,
  createClientePlano,
  getClientePlanoById,
  updateClientePlano,
  deleteClientePlano,
} from "./clientes";
export type {
  EmpresaClientePlano,
  EmpresaClientePlanoListParams,
  EmpresaClientePlanoCreatePayload,
  EmpresaClientePlanoUpdatePayload,
  EmpresaClientePlanoListResponse,
  EmpresaClientePlanoDetailResponse,
} from "./clientes/types";

// Cartões (gerenciamento de cartões para cobrança recorrente)
export {
  getCartoes,
  adicionarCartao,
  definirCartaoPadrao,
  removerCartao,
  pagarPendente,
  getPreferenciaPagamento,
  atualizarPreferenciaPagamento,
} from "./cartoes";
export type {
  CartaoEmpresa,
  TipoCartao,
  BandeiraCartao,
  AdicionarCartaoPayload,
  AdicionarCartaoResponse,
  ListarCartoesResponse,
  CartaoActionResponse,
  PagarPendenteResponse,
  MetodoPagamentoPreferido,
  PreferenciaPagamento,
  PreferenciaPagamentoResponse,
  AtualizarPreferenciaPayload,
} from "./cartoes/types";
